### ISSUE TITLE
CARPK Result Reproduce

### ISSUE THREAD

**Issue by donggoing** [flyinglynx/Bilinear-Matching-Network#15]
>[code and exemplars.zip](https://github.com/flyinglynx/Bilinear-Matching-Network/files/9349610/code.and.exemplars.zip)
Your insituition e-mail server always rejects my email. So I upload the dataloader code and exemplars here.

_Originally posted by @flyinglynx in https://github.com/flyinglynx/Bilinear-Matching-Network/issues/10#issuecomment-1216416125_

@flyinglynx Thanks for your great work, but i would like to ask how could i reproduce the reported result on CARPK with the dataloader code and exemplars? I got a validation performance of MAE 80.06, MSE 86.97 with the followed config and the pretrained params(repo).

``` yaml
DIR: 
  dataset: "/xxx/CARPK/CARPK_devkit/data/"
  exp: "bmnet+compare"
  snapshot: "exps"

DATASET:
  name: "CARPK_fixep"
  list_train: "/xxx/train.json"
  list_val: "/xxx/test.json"
  exemplar_number: 3
  downsampling_rate: 1

MODEL:
  backbone: "resnet50"
  epf_extractor: "direct_pooling"
  fix_bn: True
  ep_scale_embedding: True
  ep_scale_number: 20
  use_bias: True
  refiner: "self_similarity_module"
  matcher: "dynamic_similarity_matcher"
  counter: "density_x16"
  backbone_layer: "layer3"
  hidden_dim: 256
  refiner_layers: 1
  matcher_layers: 1
  refiner_proj_dim: 32
  matcher_proj_dim: 256
  dynamic_proj_dim: 128
  counter_dim: 257
  repeat_times: 1
  pretrain: True

TRAIN:
  resume: "model_ckpt.pth"
  counting_loss: "l2loss"
  contrast_loss: "info_nce"
  contrast_weight: 5e-6
  optimizer: "AdamW"
  device: "cuda:0"
  batch_size: 8
  epochs: 300
  lr_backbone: 1e-5
  lr: 1e-5
  lr_drop: 300 # We do not modify learning rate.
  momentum: 0.95
  weight_decay: 5e-4
  clip_max_norm: 0.1
  num_workers: 1
  seed: 430
  shots: 12

VAL:
  resume: "./model_best.pth"
  evaluate_only: True
  use_split: "val"
  visualization: False
```
